name: Test
'on': push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: pwd
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: echo "hello world"
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: echo "This is third job"